swagger: "2.0"
info:
  title: BrainBeatsWeb API 
  description: This is a BrainBeatsWeb API documentation form
  version: 1.0
  licenses:
    name: Apache 2.0
    url: "http://www.apache.org/liscences/LIS"
  servers:
    -url: http://localhost:2000
    description: Local server
    -url: http://xyz.com/
    description: Original URL
schemes: [http]


paths:

#Returns an array of users
  /api/users/getAllUsers:
    get:
      tags:
        - Users
      summary: Returns a list of all users.
      responses:
        200:    # status code
          description: Successul Response
          schema: 
            type: array
            items: 
              type: object
              properties:
                id:
                  type: integer
                name:
                  type: string

# Find user with username
  /api/users/findUser:
    post:
      tags:
        - Users
      summary: Search a user by with their username
      operationId: findUser
      description: Search a user in the database
      consumes: 
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: findUser
        required: true
        description: Find a user by their username
        schema:
          type: string
          $ref: '#/definitions/findUser'
      responses:
        200:
          description: OK
        404:
          description: URL Not Found

# Create a new user
  /api/users/createUser:
    post:
      tags:
        - Users
      summary: Create a user
      operationId: createUser
      description: Create a new user in the database
      consumes: 
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: Create
        required: true
        description: User Creation
        schema:
          $ref: '#/definitions/createUser'
      responses:
        200:
          description: OK
        404:
          description: URL Not Found

  /api/users/loginUser:
    post:
      tags:
      - Users
      summary: Checks if a user related to their password for login
      description: |
        Authenticates a user
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: loginUser
        required: true
        schema:
          $ref: '#/definitions/loginUser'
      responses:
        200:
          description: User logged in successfully
        401:
          description: bad input parameter

# Update user information
  /api/users/updateUser:
    put:
      tags:
        - Users
      summary: Update user
      operationId: updateUser
      description: Update user information
      consumes: 
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: Update
        required: true
        description: UpdateUser
        schema:
          $ref: '#/definitions/updateUser'
      responses:
        200:
          description: OK
        404:
          description: URL Not Found

# Create user posts
  /api/users/createPost:
    post:
      tags:
        - Users
      summary: Create post at user profile
      operationId: createPost
      description: Create a post for a user by username
      consumes: 
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: Create post
        required: true
        description: User Post
        schema:
          $ref: '#/definitions/createPost'
      responses:
        200:
          description: OK
        404:
          description: URL Not Found

# New user post
  /api/users/newPost:
    post:
      tags:
        - Users
      summary: Create post at user profile
      operationId: newPost
      description: Create a post for a user by username
      consumes: 
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: Create a new post
        required: true
        description: User Post
        schema:
          $ref: '#/definitions/newPost'
      responses:
        200:
          description: OK
        404:
          description: URL Not Found

# Get user posts by username
  /api/users/getPostsByUsername:
    post:
      tags:
        - Users
      summary: Search a users posts by username
      operationId: getPostsByUsername
      description: Get posts from user profile
      consumes: 
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: Posts
        required: true
        description: Get user posts by username
        schema:
          $ref: '#/definitions/getPostsByUsername'
      responses:
        200:
          description: OK
        404:
          description: URL Not Found

# Send a verification email to a user
  /api/users/sendVerificationEmail:
    post:
      tags:
        - Users
      summary: Send a user a verification email
      operationId: sendVerificationEmail
      description: Sends a user a verification email to their account's email address
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: Email
        required: true
        type: string
        schema:
          $ref: '#/definitions/sendVerificationEmail'
      responses:
        200:
          description: OK
        404:
          description: URL Not Found

# Delete a user by ID
  /api/users/deleteUser:
    delete:
      tags:
        - Users
      summary: Delete user by username
      operationId: deleteUser
      description: Delete a user from the database
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: id
        required: true
        description: Delete
        schema:
          $ref: '#/definitions/deleteUser'
      responses:
        200:
          description: OK
        404:
          description: URL Not Found
  
  # Delete a user by ID
  /api/users/midi:
    post:
      tags:
        - Users
      summary: Set up a MIDI file
      operationId: midi
      description: Creates midi at db
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: Create midi
        required: true
        description: User MIDI
        schema:
          $ref: '#/definitions/midi'
      responses:
        200:
          description: OK
        404:
          description: URL Not Found

    # Delete a user by ID
  /api/users/findMidi:
    post:
      tags:
        - Users
      summary: Set up a MIDI file
      operationId: findMidi
      description: find midi at db
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: find midi
        required: true
        description: Users MIDI
        schema:
          $ref: '#/definitions/findMidi'
      responses:
        200:
          description: OK
        404:
          description: URL Not Found

# File Upload Multiform Data
  /upload:
    post:
      tags:
        - Upload
      summary: Upload file
      consumes:
        - multipart/form-data
      parameters:
        - in: formData
          name: file
          type: file
          required: true
          description: A file to upload.
        - in: formData
          name: app
          type: string
          required: true
          description: Name of the model.
        - in: formData
          name: id
          type: string
          required: true
          description: Some random Id.
      responses:
        200:
          description: Successful Response
        400:
          description: User Error
        500:
          description: Internal Server Error

definitions:

  createUser:
    required: 
    - firstName
    - lastName
    - dob
    - email
    - username
    - password
    properties:
      firstName:
        type: string
        example: John
      lastName:
        type: string
        example: Doe
      dob: 
        type: date 
        example: 1995-03-25
      email:
        type: string
        example: JohnDoe@gmail.com
      username:
        type: string
        example: JohnDoe96
      password:
        type: string
        example: JohnDoePassword

  loginUser:
    required: 
    - email
    - password
    properties:
      email:
        type: string
        example: JohnDoe@gmail.com
      password:
        type: string
        example: JohnDoePassword

  createPost:
    required: 
    - username
    - title
    - bpm
    - key
    properties:
      username:
        type: string
        example: JohnDoe96
      title:
        type: string
        example: Post title
      bpm:
        type: int
        example: 50
      key:
        type: string
        example: C#

  newPost:
    required: 
    - username
    - title
    - bpm
    - key
    properties:
      username:
        type: string
        example: JohnDoe96
      title:
        type: string
        example: New Post title
      bpm:
        type: int
        example: 50
      key:
        type: string
        example: C#

  findUser:
    required: 
    - username
    properties:
      username:
        type: string
        example: JohnDoe96

  deleteUser:
    required:
    - id
    properties:
      id:
        type: string
        exmaple: 632961af-29ae-4c3a-8f3f-426763a4cf00

  updateUser:
    required: 
    - id
    - firstName
    - lastName
    - email
    - username
    properties:
      id:
        type: string
        example: 632961af-29ae-4c3a-8f3f-426763a4cf00
      firstName:
        type: string
        example: John
      lastName:
        type: string
        example: Doe
      dob: 
        type: date
        exmaple: 1997-07-13T00:00:00.000Z
      email:
        type: string
        example: JohnDoe@gmail.com
      username:
        type: string
        example: JohnDoe96

  getPostsByUsername:
    required:
    - username
    properties:
      username:
        type: string
        example: JohnDoe96
  
  loginUser:
    required: 
    - email
    - password
    properties:
      email:
        type: string
        example: JohnDoe@gmail.com
      password:
        type: string
        example: Secret_Password123

  midi:
    required: 
    - userId
    - bpm
    - key
    properties:
      id:
        type: string
        example: 632961af-29ae-4c3a-8f3f-426763a4cf00
      bpm:
        type: int
        example: 80
      key:
        type: string
        example: C#

  findMidi:
    required: 
    - userId
    properties:
      id:
        type: string
        example: 632961af-29ae-4c3a-8f3f-426763a4cf00

  sendVerificationEmail:
    required:
    - email
    - subject
    - text
    properties:
      email:
        type: string
        example: JohnDoe@gmail.com
      subject:
        type: string
        example: Verification Email Alert
      text:
        type: string
        example: Sending you a message in an e-mail!
    